# Change these first
owner: cloudback # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Cloudback Landing
    url: https://cloudback.it
  - name: Cloudback Web
    url: https://app.cloudback.it/health
  - name: Cloudback Identity Server
    url: https://app.cloudback.it/identity/health
  - name: Cloudback Backend Service
    url: https://app.cloudback.it/api/health
  - name: Cloudback Workers
    url: https://app.cloudback.it/health-workers

assignees: # Users to assign downtime issues (optional)
  - arxange1

status-website:
  metaTags:
    - name: "og:type"
      content: "website"
    - name: "og:title"
      content: "Cloudback Status"
    - name: "og:description"
      content: "Automatic backups of your GitHub repositories, metadata and even LFS. Backup to AWS, Azure, OneDrive, Google Cloud, and more. Instant restores and notifications."
    - name: "og:image"
      content: "https://framerusercontent.com/images/AjNcufZGlRJ6GrC1bPajejWGUs.png"
    - name: "og:url"
      content: "https://cloudback.it/"
    - name: "description"
      content: "Automatic backups of your GitHub repositories, metadata and even LFS. Backup to AWS, Azure, OneDrive, Google Cloud, and more. Instant restores and notifications."
  themeUrl: https://status.cloudback.it/custom.css
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cloudback.it
  name: Cloudback Status Page
  # baseUrl: /
  customHeadHtml: > 
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">"
  logoUrl: https://raw.githubusercontent.com/cloudback/status/main/assets/logo.svg
  favicon: https://raw.githubusercontent.com/cloudback/status/main/assets/logo.png
  faviconSvg: https://raw.githubusercontent.com/cloudback/status/main/assets/logo.svg
  introTitle: "The reliable way to back up GitHub repositories"
  introMessage: Automatic daily backups and instant restores of your GitHub repositories, metadata, and even LFS. Backup to any storage you want.
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://cloudback.it
    - title: GitHub
      href: https://github.com/$OWNER/
i18n:
  footer: >
    © 2024 Cloudback  
    
    [support@cloudback.it](mailto:support@cloudback.it)  
    
    This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
